# site settings

title: Kirubel | Rice University Engineer
description: Portfolio Site and blog for Kirubel
taglong: Portfolio Site and blog for Kirubel
tagshort: Kirubel's page
url: https://cvless.netlify.app
baseurl: ""
permalink: pretty
repo: https://github.com/kirubel-g/kirubel-g.github.io

# author settings

author:
  name: Kirubel Ghebreab
  email: kirubel.wg@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: kirubel-g
  linkedin: https://www.linkedin.com/in/kirubel-ghebreab-2a614a19b/

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
